MLIR: lib/ExecutionEngine/CudaRuntimeWrappers.cpp File Reference
CudaRuntimeWrappers.cpp File Reference
#include "mlir/ExecutionEngine/CRunnerUtils.h"
#include <stdio.h>
#include "cuda.h"
#include "cusparse.h"
Classes
class ScopedContext
Macros
#define MLIR_CUDA_WRAPPERS_EXPORT
#define CUDA_REPORT_IF_ERROR(expr)
#define CUSPARSE_REPORT_IF_ERROR(expr)
#define ALPHABETA(w, alpha, beta)
Functions
MLIR_CUDA_WRAPPERS_EXPORT CUmodule mgpuModuleLoad (void *data)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuModuleUnload (CUmodule module)
MLIR_CUDA_WRAPPERS_EXPORT CUfunction mgpuModuleGetFunction (CUmodule module, const char *name)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuLaunchKernel (CUfunction function, intptr_t gridX, intptr_t gridY, intptr_t gridZ, intptr_t blockX, intptr_t blockY, intptr_t blockZ, int32_t smem, CUstream stream, void **params, void **extra)
MLIR_CUDA_WRAPPERS_EXPORT CUstream mgpuStreamCreate ()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuStreamDestroy (CUstream stream)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuStreamSynchronize (CUstream stream)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuStreamWaitEvent (CUstream stream, CUevent event)
MLIR_CUDA_WRAPPERS_EXPORT CUevent mgpuEventCreate ()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuEventDestroy (CUevent event)
MLIR_CUDA_WRAPPERS_EXPORT C void mgpuEventSynchronize (CUevent event)
MLIR_CUDA_WRAPPERS_EXPORT C void mgpuEventRecord (CUevent event, CUstream stream)
void * mgpuMemAlloc (uint64_t sizeBytes, CUstream)
void mgpuMemFree (void *ptr, CUstream)
void mgpuMemcpy (void *dst, void *src, size_t sizeBytes, CUstream stream)
void mgpuMemset32 (void *dst, unsigned int value, size_t count, CUstream stream)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuMemHostRegister (void *ptr, uint64_t sizeBytes)
Helper functions for writing mlir example code.
MLIR_CUDA_WRAPPERS_EXPORT void mgpuMemHostRegisterMemRef (int64_t rank, StridedMemRefType< char, 1 > *descriptor, int64_t elementSizeBytes)
Registers a memref with the CUDA runtime.
MLIR_CUDA_WRAPPERS_EXPORT void mgpuMemHostUnregister (void *ptr)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuMemHostUnregisterMemRef (int64_t rank, StridedMemRefType< char, 1 > *descriptor, int64_t elementSizeBytes)
Unregisters a memref with the CUDA runtime.
MLIR_CUDA_WRAPPERS_EXPORT void mgpuSetDefaultDevice (int32_t device)
static cudaDataType_t dataTp (int32_t width)
Wrapper methods for the cuSparse library.
static cusparseIndexType_t idxTp (int32_t width)
MLIR_CUDA_WRAPPERS_EXPORT void * mgpuCreateSparseEnv (CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuDestroySparseEnv (void *h, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void * mgpuCreateDnVec (intptr_t size, void *values, int32_t dw, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuDestroyDnVec (void *v, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void * mgpuCreateDnMat (intptr_t rows, intptr_t cols, void *values, int32_t dw, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuDestroyDnMat (void *m, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void * mgpuCreateCoo (intptr_t rows, intptr_t cols, intptr_t nnz, void *rowIdxs, void *colIdxs, void *values, int32_t iw, int32_t dw, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void * mgpuCreateCsr (intptr_t rows, intptr_t cols, intptr_t nnz, void *rowPos, void *colIdxs, void *values, int32_t pw, int32_t iw, int32_t dw, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuDestroySpMat (void *m, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT intptr_t mgpuSpMVBufferSize (void *h, int32_t ma, void *a, void *x, void *y, int32_t dw, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuSpMV (void *h, int32_t ma, void *a, void *x, void *y, int32_t dw, void *buf, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT intptr_t mgpuSpMMBufferSize (void *h, int32_t ma, int32_t mb, void *a, void *b, void *c, int32_t dw, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuSpMM (void *h, int32_t ma, int32_t mb, void *a, void *b, void *c, int32_t dw, void *buf, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT intptr_t mgpuSDDMMBufferSize (void *h, int32_t ma, int32_t mb, void *a, void *b, void *c, int32_t dw, CUstream)
MLIR_CUDA_WRAPPERS_EXPORT void mgpuSDDMM (void *h, int32_t ma, int32_t mb, void *a, void *b, void *c, int32_t dw, void *buf, CUstream)
Variables
static thread_local int32_t defaultDevice = 0
Macro Definition Documentation
ALPHABETA
#define ALPHABETA (w, alpha, beta)
Value:
  float(alpha##f) = 1.0f;                                                      \
  float(beta##f) = 1.0f;                                                       \
  double(alpha##d) = 1.0;                                                      \
  double(beta##d) = 1.0;                                                       \
  const void *(alpha##p) = nullptr;                                            \
  const void *(beta##p) = nullptr;                                             \
  if ((w) == 32) {                                                             \
    (alpha##p) = reinterpret_cast<void *>(&(alpha##f));                        \
    (beta##p) = reinterpret_cast<void *>(&(beta##f));                          \
  } else {                                                                     \
    (alpha##p) = reinterpret_cast<void *>(&(alpha##d));                        \
    (beta##p) = reinterpret_cast<void *>(&(beta##d));                          \
  }
Definition at line 250 of file CudaRuntimeWrappers.cpp.
CUDA_REPORT_IF_ERROR
#define CUDA_REPORT_IF_ERROR (expr)
Value:
  [](CUresult result) {                                                        \
    if (!result)                                                               \
      return;                                                                  \
    const char *name = nullptr;                                                \
    cuGetErrorName(result, &name);                                             \
    if (!name)                                                                 \
      name = "<unknown>";                                                      \
    fprintf(stderr, "'%s' failed with '%s'\n", #expr, name);                   \
  }(expr)
Definition at line 28 of file CudaRuntimeWrappers.cpp.
CUSPARSE_REPORT_IF_ERROR
#define CUSPARSE_REPORT_IF_ERROR (expr)
Value:
  {                                                                            \
    cusparseStatus_t status = (expr);                                          \
    if (status != CUSPARSE_STATUS_SUCCESS) {                                   \
      fprintf(stderr, "cuSPARSE '%s' failed with '%s'\n", #expr,               \
              cusparseGetErrorString(status));                                 \
    }                                                                          \
  }
Definition at line 39 of file CudaRuntimeWrappers.cpp.
MLIR_CUDA_WRAPPERS_EXPORT
#define MLIR_CUDA_WRAPPERS_EXPORT
Definition at line 25 of file CudaRuntimeWrappers.cpp.
Function Documentation
dataTp()
static cudaDataType_t dataTp (int32_t width) inline static
Wrapper methods for the cuSparse library.
Definition at line 231 of file CudaRuntimeWrappers.cpp.
Referenced by mgpuCreateCoo(), mgpuCreateCsr(), mgpuCreateDnMat(), mgpuCreateDnVec(), mgpuSDDMM(), mgpuSDDMMBufferSize(), mgpuSpMM(), mgpuSpMMBufferSize(), mgpuSpMV(), and mgpuSpMVBufferSize().
idxTp()
static cusparseIndexType_t idxTp (int32_t width) inline static
Definition at line 240 of file CudaRuntimeWrappers.cpp.
Referenced by mgpuCreateCoo(), and mgpuCreateCsr().
mgpuCreateCoo()
MLIR_CUDA_WRAPPERS_EXPORT void* mgpuCreateCoo (intptr_t rows, intptr_t cols, intptr_t nnz, void * rowIdxs, void * colIdxs, void * values, int32_t iw, int32_t dw, CUstream)
Definition at line 309 of file CudaRuntimeWrappers.cpp.
References CUSPARSE_REPORT_IF_ERROR, dataTp(), and idxTp().
mgpuCreateCsr()
MLIR_CUDA_WRAPPERS_EXPORT void* mgpuCreateCsr (intptr_t rows, intptr_t cols, intptr_t nnz, void * rowPos, void * colIdxs, void * values, int32_t pw, int32_t iw, int32_t dw, CUstream)
Definition at line 322 of file CudaRuntimeWrappers.cpp.
References CUSPARSE_REPORT_IF_ERROR, dataTp(), and idxTp().
mgpuCreateDnMat()
MLIR_CUDA_WRAPPERS_EXPORT void* mgpuCreateDnMat (intptr_t rows, intptr_t cols, void * values, int32_t dw, CUstream)
Definition at line 293 of file CudaRuntimeWrappers.cpp.
References CUSPARSE_REPORT_IF_ERROR, and dataTp().
mgpuCreateDnVec()
MLIR_CUDA_WRAPPERS_EXPORT void* mgpuCreateDnVec (intptr_t size, void * values, int32_t dw, CUstream)
Definition at line 279 of file CudaRuntimeWrappers.cpp.
References CUSPARSE_REPORT_IF_ERROR, and dataTp().
mgpuCreateSparseEnv()
MLIR_CUDA_WRAPPERS_EXPORT void* mgpuCreateSparseEnv (CUstream)
Definition at line 266 of file CudaRuntimeWrappers.cpp.
References CUSPARSE_REPORT_IF_ERROR.
mgpuDestroyDnMat()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuDestroyDnMat (void * m, CUstream)
Definition at line 303 of file CudaRuntimeWrappers.cpp.
References CUSPARSE_REPORT_IF_ERROR.
mgpuDestroyDnVec()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuDestroyDnVec (void * v, CUstream)
Definition at line 287 of file CudaRuntimeWrappers.cpp.
References CUSPARSE_REPORT_IF_ERROR.
mgpuDestroySparseEnv()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuDestroySparseEnv (void * h, CUstream)
Definition at line 273 of file CudaRuntimeWrappers.cpp.
References CUSPARSE_REPORT_IF_ERROR.
mgpuDestroySpMat()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuDestroySpMat (void * m, CUstream)
Definition at line 336 of file CudaRuntimeWrappers.cpp.
References CUSPARSE_REPORT_IF_ERROR.
mgpuEventCreate()
MLIR_CUDA_WRAPPERS_EXPORT CUevent mgpuEventCreate ()
Definition at line 127 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuEventDestroy()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuEventDestroy (CUevent event)
Definition at line 134 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuEventRecord()
MLIR_CUDA_WRAPPERS_EXPORT C void mgpuEventRecord (CUevent event, CUstream stream)
Definition at line 142 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuEventSynchronize()
MLIR_CUDA_WRAPPERS_EXPORT C void mgpuEventSynchronize (CUevent event)
Definition at line 138 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuLaunchKernel()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuLaunchKernel (CUfunction function, intptr_t gridX, intptr_t gridY, intptr_t gridZ, intptr_t blockX, intptr_t blockY, intptr_t blockZ, int32_t smem, CUstream stream, void ** params, void ** extra)
Definition at line 96 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuMemAlloc()
void* mgpuMemAlloc (uint64_t sizeBytes, CUstream)
Definition at line 147 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuMemcpy()
void mgpuMemcpy (void * dst, void * src, size_t sizeBytes, CUstream stream)
Definition at line 158 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuMemFree()
void mgpuMemFree (void * ptr, CUstream)
Definition at line 154 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuMemHostRegister()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuMemHostRegister (void * ptr, uint64_t sizeBytes)
Helper functions for writing mlir example code.
Definition at line 178 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
Referenced by mgpuMemHostRegisterMemRef().
mgpuMemHostRegisterMemRef()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuMemHostRegisterMemRef (int64_t rank, StridedMemRefType< char, 1 > * descriptor, int64_t elementSizeBytes)
Registers a memref with the CUDA runtime.
descriptor is a pointer to a ranked memref descriptor struct of rank rank. Helpful until we have transfer functions implemented.
Definition at line 187 of file CudaRuntimeWrappers.cpp.
References StridedMemRefType< T, N >::data, mgpuMemHostRegister(), StridedMemRefType< T, N >::offset, and StridedMemRefType< T, N >::sizes.
mgpuMemHostUnregister()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuMemHostUnregister (void * ptr)
Definition at line 208 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
Referenced by mgpuMemHostUnregisterMemRef().
mgpuMemHostUnregisterMemRef()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuMemHostUnregisterMemRef (int64_t rank, StridedMemRefType< char, 1 > * descriptor, int64_t elementSizeBytes)
Unregisters a memref with the CUDA runtime.
descriptor is a pointer to a ranked memref descriptor struct of rank rank
Definition at line 216 of file CudaRuntimeWrappers.cpp.
References StridedMemRefType< T, N >::data, mgpuMemHostUnregister(), and StridedMemRefType< T, N >::offset.
mgpuMemset32()
void mgpuMemset32 (void * dst, unsigned int value, size_t count, CUstream stream)
Definition at line 165 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuModuleGetFunction()
MLIR_CUDA_WRAPPERS_EXPORT CUfunction mgpuModuleGetFunction (CUmodule module, const char * name)
Definition at line 86 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuModuleLoad()
MLIR_CUDA_WRAPPERS_EXPORT CUmodule mgpuModuleLoad (void * data)
Definition at line 74 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuModuleUnload()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuModuleUnload (CUmodule module)
Definition at line 81 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuSDDMM()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuSDDMM (void * h, int32_t ma, int32_t mb, void * a, void * b, void * c, int32_t dw, void * buf, CUstream)
Definition at line 427 of file CudaRuntimeWrappers.cpp.
References ALPHABETA, CUSPARSE_REPORT_IF_ERROR, and dataTp().
mgpuSDDMMBufferSize()
MLIR_CUDA_WRAPPERS_EXPORT intptr_t mgpuSDDMMBufferSize (void * h, int32_t ma, int32_t mb, void * a, void * b, void * c, int32_t dw, CUstream)
Definition at line 409 of file CudaRuntimeWrappers.cpp.
References ALPHABETA, CUSPARSE_REPORT_IF_ERROR, and dataTp().
mgpuSetDefaultDevice()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuSetDefaultDevice (int32_t device)
Definition at line 223 of file CudaRuntimeWrappers.cpp.
References defaultDevice.
mgpuSpMM()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuSpMM (void * h, int32_t ma, int32_t mb, void * a, void * b, void * c, int32_t dw, void * buf, CUstream)
Definition at line 393 of file CudaRuntimeWrappers.cpp.
References ALPHABETA, CUSPARSE_REPORT_IF_ERROR, and dataTp().
mgpuSpMMBufferSize()
MLIR_CUDA_WRAPPERS_EXPORT intptr_t mgpuSpMMBufferSize (void * h, int32_t ma, int32_t mb, void * a, void * b, void * c, int32_t dw, CUstream)
Definition at line 375 of file CudaRuntimeWrappers.cpp.
References ALPHABETA, CUSPARSE_REPORT_IF_ERROR, and dataTp().
mgpuSpMV()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuSpMV (void * h, int32_t ma, void * a, void * x, void * y, int32_t dw, void * buf, CUstream)
Definition at line 358 of file CudaRuntimeWrappers.cpp.
References ALPHABETA, CUSPARSE_REPORT_IF_ERROR, and dataTp().
mgpuSpMVBufferSize()
MLIR_CUDA_WRAPPERS_EXPORT intptr_t mgpuSpMVBufferSize (void * h, int32_t ma, void * a, void * x, void * y, int32_t dw, CUstream)
Definition at line 342 of file CudaRuntimeWrappers.cpp.
References ALPHABETA, CUSPARSE_REPORT_IF_ERROR, and dataTp().
mgpuStreamCreate()
MLIR_CUDA_WRAPPERS_EXPORT CUstream mgpuStreamCreate ()
Definition at line 106 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuStreamDestroy()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuStreamDestroy (CUstream stream)
Definition at line 113 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuStreamSynchronize()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuStreamSynchronize (CUstream stream)
Definition at line 118 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
mgpuStreamWaitEvent()
MLIR_CUDA_WRAPPERS_EXPORT void mgpuStreamWaitEvent (CUstream stream, CUevent event)
Definition at line 122 of file CudaRuntimeWrappers.cpp.
References CUDA_REPORT_IF_ERROR.
Variable Documentation
defaultDevice
thread_local int32_t defaultDevice = 0 static
Definition at line 48 of file CudaRuntimeWrappers.cpp.
Referenced by mgpuSetDefaultDevice(), and ScopedContext::ScopedContext().