MLIR: include/mlir/CAPI/Diagnostics.h File Reference
Diagnostics.h File Reference
#include "mlir-c/Diagnostics.h"
#include <cassert>
Namespaces
mlir
This header declares functions that assit transformations in the MemRef dialect.
Functions
mlir::Diagnostic & unwrap (MlirDiagnostic diagnostic)
MlirDiagnostic wrap (mlir::Diagnostic &diagnostic)
Function Documentation
unwrap()
mlir::Diagnostic& unwrap (MlirDiagnostic diagnostic) inline
Definition at line 19 of file Diagnostics.h.
References MlirDiagnostic::ptr.
Referenced by llvm::GraphTraits< const mlir::CallGraphNode * >::child_begin(), llvm::GraphTraits< const mlir::CallGraphNode * >::child_end(), getDenseAttribute(), getDenseResource(), getDenseResourceVal(), mlir::ExternalPass::initialize(), mlir::python::PyGlobals::lookupTypeCaster(), MLIR_DEFINE_CAPI_DIALECT_REGISTRATION(), mlirAffineAddExprGet(), mlirAffineBinaryOpExprGetLHS(), mlirAffineBinaryOpExprGetRHS(), mlirAffineCeilDivExprGet(), mlirAffineConstantExprGet(), mlirAffineConstantExprGetValue(), mlirAffineDimExprGet(), mlirAffineDimExprGetPosition(), mlirAffineExprCompose(), mlirAffineExprDump(), mlirAffineExprEqual(), mlirAffineExprGetContext(), mlirAffineExprGetLargestKnownDivisor(), mlirAffineExprIsAAdd(), mlirAffineExprIsABinary(), mlirAffineExprIsACeilDiv(), mlirAffineExprIsAConstant(), mlirAffineExprIsADim(), mlirAffineExprIsAFloorDiv(), mlirAffineExprIsAMod(), mlirAffineExprIsAMul(), mlirAffineExprIsASymbol(), mlirAffineExprIsFunctionOfDim(), mlirAffineExprIsMultipleOf(), mlirAffineExprIsPureAffine(), mlirAffineExprIsSymbolicOrConstant(), mlirAffineExprPrint(), mlirAffineFloorDivExprGet(), mlirAffineMapAttrGet(), mlirAffineMapAttrGetValue(), mlirAffineMapCompressUnusedSymbols(), mlirAffineMapConstantGet(), mlirAffineMapDump(), mlirAffineMapEmptyGet(), mlirAffineMapEqual(), mlirAffineMapGet(), mlirAffineMapGetContext(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetNumDims(), mlirAffineMapGetNumInputs(), mlirAffineMapGetNumResults(), mlirAffineMapGetNumSymbols(), mlirAffineMapGetResult(), mlirAffineMapGetSingleConstantResult(), mlirAffineMapGetSubMap(), mlirAffineMapIsEmpty(), mlirAffineMapIsIdentity(), mlirAffineMapIsMinorIdentity(), mlirAffineMapIsPermutation(), mlirAffineMapIsProjectedPermutation(), mlirAffineMapIsSingleConstant(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), mlirAffineMapPrint(), mlirAffineMapReplace(), mlirAffineMapZeroResultGet(), mlirAffineModExprGet(), mlirAffineMulExprGet(), mlirAffineSymbolExprGet(), mlirAffineSymbolExprGetPosition(), mlirAnyQuantizedTypeGet(), mlirArrayAttrGet(), mlirArrayAttrGetElement(), mlirArrayAttrGetNumElements(), mlirAttributeDump(), mlirAttributeEqual(), mlirAttributeGetContext(), mlirAttributeGetType(), mlirAttributeGetTypeID(), mlirAttributeIsAAffineMap(), mlirAttributeIsAArray(), mlirAttributeIsABool(), mlirAttributeIsADenseBoolArray(), mlirAttributeIsADenseElements(), mlirAttributeIsADenseF32Array(), mlirAttributeIsADenseF64Array(), mlirAttributeIsADenseFPElements(), mlirAttributeIsADenseI16Array(), mlirAttributeIsADenseI32Array(), mlirAttributeIsADenseI64Array(), mlirAttributeIsADenseI8Array(), mlirAttributeIsADenseIntElements(), mlirAttributeIsADictionary(), mlirAttributeIsAElements(), mlirAttributeIsAFlatSymbolRef(), mlirAttributeIsAFloat(), mlirAttributeIsAInteger(), mlirAttributeIsAIntegerSet(), mlirAttributeIsALocation(), mlirAttributeIsAOpaque(), mlirAttributeIsASparseElements(), mlirAttributeIsASparseTensorEncodingAttr(), mlirAttributeIsAStridedLayout(), mlirAttributeIsAString(), mlirAttributeIsASymbolRef(), mlirAttributeIsAType(), mlirAttributeIsAUnit(), mlirAttributeParseGet(), mlirAttributePrint(), mlirBF16TypeGet(), mlirBlockAddArgument(), mlirBlockAppendOwnedOperation(), mlirBlockArgumentGetArgNumber(), mlirBlockArgumentGetOwner(), mlirBlockArgumentSetType(), mlirBlockCreate(), mlirBlockDestroy(), mlirBlockDetach(), mlirBlockEqual(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNextInRegion(), mlirBlockGetNumArguments(), mlirBlockGetParentOperation(), mlirBlockGetParentRegion(), mlirBlockGetTerminator(), mlirBlockInsertOwnedOperation(), mlirBlockInsertOwnedOperationAfter(), mlirBlockInsertOwnedOperationBefore(), mlirBlockPrint(), mlirBoolAttrGet(), mlirBoolAttrGetValue(), mlirBytecodeWriterConfigDesiredEmitVersion(), mlirBytecodeWriterConfigDestroy(), mlirCalibratedQuantizedTypeGet(), mlirCalibratedQuantizedTypeGetMax(), mlirCalibratedQuantizedTypeGetMin(), mlirComplexTypeGet(), mlirComplexTypeGetElementType(), mlirContextAppendDialectRegistry(), mlirContextAttachDiagnosticHandler(), mlirContextDestroy(), mlirContextDetachDiagnosticHandler(), mlirContextEnableMultithreading(), mlirContextEqual(), mlirContextGetAllowUnregisteredDialects(), mlirContextGetNumLoadedDialects(), mlirContextGetNumRegisteredDialects(), mlirContextGetOrLoadDialect(), mlirContextIsRegisteredOperation(), mlirContextLoadAllAvailableDialects(), mlirContextSetAllowUnregisteredDialects(), mlirCreateExternalPass(), mlirDenseArrayGetNumElements(), mlirDenseBoolArrayGet(), mlirDenseBoolArrayGetElement(), mlirDenseElementsAttrBoolGet(), mlirDenseElementsAttrBoolSplatGet(), mlirDenseElementsAttrDoubleSplatGet(), mlirDenseElementsAttrFloatSplatGet(), mlirDenseElementsAttrGet(), mlirDenseElementsAttrGetBoolSplatValue(), mlirDenseElementsAttrGetBoolValue(), mlirDenseElementsAttrGetDoubleSplatValue(), mlirDenseElementsAttrGetDoubleValue(), mlirDenseElementsAttrGetFloatSplatValue(), mlirDenseElementsAttrGetFloatValue(), mlirDenseElementsAttrGetInt16Value(), mlirDenseElementsAttrGetInt32SplatValue(), mlirDenseElementsAttrGetInt32Value(), mlirDenseElementsAttrGetInt64SplatValue(), mlirDenseElementsAttrGetInt64Value(), mlirDenseElementsAttrGetInt8SplatValue(), mlirDenseElementsAttrGetInt8Value(), mlirDenseElementsAttrGetRawData(), mlirDenseElementsAttrGetSplatValue(), mlirDenseElementsAttrGetStringSplatValue(), mlirDenseElementsAttrGetStringValue(), mlirDenseElementsAttrGetUInt16Value(), mlirDenseElementsAttrGetUInt32SplatValue(), mlirDenseElementsAttrGetUInt32Value(), mlirDenseElementsAttrGetUInt64SplatValue(), mlirDenseElementsAttrGetUInt64Value(), mlirDenseElementsAttrGetUInt8SplatValue(), mlirDenseElementsAttrGetUInt8Value(), mlirDenseElementsAttrInt32SplatGet(), mlirDenseElementsAttrInt64SplatGet(), mlirDenseElementsAttrInt8SplatGet(), mlirDenseElementsAttrIsSplat(), mlirDenseElementsAttrRawBufferGet(), mlirDenseElementsAttrReshapeGet(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrStringGet(), mlirDenseElementsAttrUInt32SplatGet(), mlirDenseElementsAttrUInt64SplatGet(), mlirDenseElementsAttrUInt8SplatGet(), mlirDenseF32ArrayGet(), mlirDenseF32ArrayGetElement(), mlirDenseF64ArrayGet(), mlirDenseF64ArrayGetElement(), mlirDenseI16ArrayGet(), mlirDenseI16ArrayGetElement(), mlirDenseI32ArrayGet(), mlirDenseI32ArrayGetElement(), mlirDenseI64ArrayGet(), mlirDenseI64ArrayGetElement(), mlirDenseI8ArrayGet(), mlirDenseI8ArrayGetElement(), mlirDiagnosticGetLocation(), mlirDiagnosticGetNote(), mlirDiagnosticGetNumNotes(), mlirDiagnosticGetSeverity(), mlirDiagnosticPrint(), mlirDialectEqual(), mlirDialectGetContext(), mlirDialectGetNamespace(), mlirDialectRegistryDestroy(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirDictionaryAttrGetNumElements(), mlirElementsAttrGetNumElements(), mlirElementsAttrGetValue(), mlirElementsAttrIsValidIndex(), mlirEmitError(), mlirExecutionEngineDestroy(), mlirExecutionEngineDumpToObjectFile(), mlirExecutionEngineInvokePacked(), mlirExecutionEngineLookup(), mlirExecutionEngineLookupPacked(), mlirExecutionEngineRegisterSymbol(), mlirExternalPassSignalFailure(), mlirF16TypeGet(), mlirF32TypeGet(), mlirF64TypeGet(), mlirFlatSymbolRefAttrGet(), mlirFlatSymbolRefAttrGetValue(), mlirFloat8E4M3B11FNUZTypeGet(), mlirFloat8E4M3FNTypeGet(), mlirFloat8E4M3FNUZTypeGet(), mlirFloat8E5M2FNUZTypeGet(), mlirFloat8E5M2TypeGet(), mlirFloatAttrDoubleGet(), mlirFloatAttrDoubleGetChecked(), mlirFloatAttrGetValueDouble(), mlirFunctionTypeGet(), mlirFunctionTypeGetInput(), mlirFunctionTypeGetNumInputs(), mlirFunctionTypeGetNumResults(), mlirFunctionTypeGetResult(), mlirIdentifierEqual(), mlirIdentifierGet(), mlirIdentifierGetContext(), mlirIdentifierStr(), mlirIndexTypeGet(), mlirInferShapedTypeOpInterfaceInferReturnTypes(), mlirInferTypeOpInterfaceInferReturnTypes(), mlirIntegerAttrGet(), mlirIntegerAttrGetValueInt(), mlirIntegerAttrGetValueSInt(), mlirIntegerAttrGetValueUInt(), mlirIntegerSetDump(), mlirIntegerSetEmptyGet(), mlirIntegerSetEqual(), mlirIntegerSetGetConstraint(), mlirIntegerSetGetContext(), mlirIntegerSetGetNumConstraints(), mlirIntegerSetGetNumDims(), mlirIntegerSetGetNumEqualities(), mlirIntegerSetGetNumInequalities(), mlirIntegerSetGetNumInputs(), mlirIntegerSetGetNumSymbols(), mlirIntegerSetIsCanonicalEmpty(), mlirIntegerSetIsConstraintEq(), mlirIntegerSetPrint(), mlirIntegerSetReplaceGet(), mlirIntegerTypeGet(), mlirIntegerTypeGetWidth(), mlirIntegerTypeIsSigned(), mlirIntegerTypeIsSignless(), mlirIntegerTypeIsUnsigned(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirLLVMArrayTypeGet(), mlirLLVMFunctionTypeGet(), mlirLLVMPointerTypeGet(), mlirLLVMStructTypeLiteralGet(), mlirLLVMVoidTypeGet(), mlirLocationCallSiteGet(), mlirLocationEqual(), mlirLocationFileLineColGet(), mlirLocationFromAttribute(), mlirLocationFusedGet(), mlirLocationGetAttribute(), mlirLocationGetContext(), mlirLocationNameGet(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirMemRefTypeContiguousGet(), mlirMemRefTypeContiguousGetChecked(), mlirMemRefTypeGet(), mlirMemRefTypeGetAffineMap(), mlirMemRefTypeGetChecked(), mlirMemRefTypeGetLayout(), mlirMemRefTypeGetMemorySpace(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleDestroy(), mlirModuleGetBody(), mlirModuleGetContext(), mlirModuleGetOperation(), mlirNoneTypeGet(), mlirOpaqueAttrGet(), mlirOpaqueAttrGetData(), mlirOpaqueAttrGetDialectNamespace(), mlirOpaqueTypeGet(), mlirOpaqueTypeGetData(), mlirOpaqueTypeGetDialectNamespace(), mlirOperationCreate(), mlirOperationCreateParse(), mlirOperationImplementsInterface(), mlirOperationImplementsInterfaceStatic(), mlirOpOperandGetNextUse(), mlirOpOperandGetOperandNumber(), mlirOpOperandGetOwner(), mlirOpPassManagerAddOwnedPass(), mlirOpPassManagerAddPipeline(), mlirOpPassManagerGetNestedUnder(), mlirOpPrintingFlagsAssumeVerified(), mlirOpPrintingFlagsDestroy(), mlirOpPrintingFlagsElideLargeElementsAttrs(), mlirOpPrintingFlagsEnableDebugInfo(), mlirOpPrintingFlagsPrintGenericOpForm(), mlirOpPrintingFlagsUseLocalScope(), mlirOpResultGetOwner(), mlirOpResultGetResultNumber(), mlirParsePassPipeline(), mlirPassManagerAddOwnedPass(), mlirPassManagerCreate(), mlirPassManagerCreateOnOperation(), mlirPassManagerDestroy(), mlirPassManagerEnableIRPrinting(), mlirPassManagerEnableVerifier(), mlirPassManagerGetAsOpPassManager(), mlirPassManagerGetNestedUnder(), mlirPDLAttributeTypeGet(), mlirPDLOperationTypeGet(), mlirPDLRangeTypeGet(), mlirPDLRangeTypeGetElementType(), mlirPDLTypeTypeGet(), mlirPDLValueTypeGet(), mlirPrintPassPipeline(), mlirQuantizedTypeCastExpressedToStorageType(), mlirQuantizedTypeCastFromExpressedType(), mlirQuantizedTypeCastFromStorageType(), mlirQuantizedTypeCastToExpressedType(), mlirQuantizedTypeCastToStorageType(), mlirQuantizedTypeGetExpressedType(), mlirQuantizedTypeGetFlags(), mlirQuantizedTypeGetQuantizedElementType(), mlirQuantizedTypeGetStorageType(), mlirQuantizedTypeGetStorageTypeIntegralWidth(), mlirQuantizedTypeGetStorageTypeMax(), mlirQuantizedTypeGetStorageTypeMin(), mlirQuantizedTypeIsCompatibleExpressedType(), mlirQuantizedTypeIsSigned(), mlirRankedTensorTypeGet(), mlirRankedTensorTypeGetChecked(), mlirRankedTensorTypeGetEncoding(), mlirRegionAppendOwnedBlock(), mlirRegionEqual(), mlirRegionGetFirstBlock(), mlirRegionGetNextInOperation(), mlirRegionInsertOwnedBlock(), mlirRegionInsertOwnedBlockAfter(), mlirRegionInsertOwnedBlockBefore(), mlirRegisterAllDialects(), mlirRegisterAllLLVMTranslations(), mlirShapedTypeGetDimSize(), mlirShapedTypeGetElementType(), mlirShapedTypeGetRank(), mlirShapedTypeHasRank(), mlirShapedTypeHasStaticShape(), mlirShapedTypeIsDynamicDim(), mlirSparseElementsAttrGetIndices(), mlirSparseElementsAttrGetValues(), mlirSparseElementsAttribute(), mlirSparseTensorEncodingAttrGet(), mlirSparseTensorEncodingAttrGetCrdWidth(), mlirSparseTensorEncodingAttrGetDimOrdering(), mlirSparseTensorEncodingAttrGetHigherOrdering(), mlirSparseTensorEncodingAttrGetLvlType(), mlirSparseTensorEncodingAttrGetPosWidth(), mlirSparseTensorEncodingGetLvlRank(), mlirStridedLayoutAttrGet(), mlirStridedLayoutAttrGetNumStrides(), mlirStridedLayoutAttrGetOffset(), mlirStridedLayoutAttrGetStride(), mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirSymbolRefAttrGet(), mlirSymbolRefAttrGetLeafReference(), mlirSymbolRefAttrGetNestedReference(), mlirSymbolRefAttrGetNumNestedReferences(), mlirSymbolRefAttrGetRootReference(), mlirSymbolTableCreate(), mlirSymbolTableDestroy(), mlirSymbolTableErase(), mlirSymbolTableInsert(), mlirSymbolTableLookup(), mlirSymbolTableReplaceAllSymbolUses(), mlirSymbolTableWalkSymbolTables(), mlirTransformAnyOpTypeGet(), mlirTransformOperationTypeGet(), mlirTransformOperationTypeGetOperationName(), mlirTupleTypeGet(), mlirTupleTypeGetNumTypes(), mlirTupleTypeGetType(), mlirTypeAttrGet(), mlirTypeAttrGetValue(), mlirTypeDump(), mlirTypeEqual(), mlirTypeGetContext(), mlirTypeGetDialect(), mlirTypeGetTypeID(), mlirTypeIDAllocatorAllocateTypeID(), mlirTypeIDAllocatorDestroy(), mlirTypeIDEqual(), mlirTypeIDHashValue(), mlirTypeIsAAnyQuantizedType(), mlirTypeIsABF16(), mlirTypeIsACalibratedQuantizedType(), mlirTypeIsAComplex(), mlirTypeIsAF16(), mlirTypeIsAF32(), mlirTypeIsAF64(), mlirTypeIsAFloat8E4M3B11FNUZ(), mlirTypeIsAFloat8E4M3FN(), mlirTypeIsAFloat8E4M3FNUZ(), mlirTypeIsAFloat8E5M2(), mlirTypeIsAFloat8E5M2FNUZ(), mlirTypeIsAFunction(), mlirTypeIsAIndex(), mlirTypeIsAInteger(), mlirTypeIsAMemRef(), mlirTypeIsANone(), mlirTypeIsAOpaque(), mlirTypeIsAPDLAttributeType(), mlirTypeIsAPDLOperationType(), mlirTypeIsAPDLRangeType(), mlirTypeIsAPDLType(), mlirTypeIsAPDLTypeType(), mlirTypeIsAPDLValueType(), mlirTypeIsAQuantizedType(), mlirTypeIsARankedTensor(), mlirTypeIsAShaped(), mlirTypeIsATensor(), mlirTypeIsATransformOperationType(), mlirTypeIsATuple(), mlirTypeIsAUniformQuantizedPerAxisType(), mlirTypeIsAUniformQuantizedType(), mlirTypeIsAUnrankedMemRef(), mlirTypeIsAUnrankedTensor(), mlirTypeIsAVector(), mlirTypeParseGet(), mlirTypePrint(), mlirUniformQuantizedPerAxisTypeGet(), mlirUniformQuantizedPerAxisTypeGetNumDims(), mlirUniformQuantizedPerAxisTypeGetQuantizedDimension(), mlirUniformQuantizedPerAxisTypeGetScale(), mlirUniformQuantizedPerAxisTypeGetZeroPoint(), mlirUniformQuantizedPerAxisTypeIsFixedPoint(), mlirUniformQuantizedTypeGet(), mlirUniformQuantizedTypeGetScale(), mlirUniformQuantizedTypeGetZeroPoint(), mlirUniformQuantizedTypeIsFixedPoint(), mlirUnitAttrGet(), mlirUnrankedMemrefGetMemorySpace(), mlirUnrankedMemRefTypeGet(), mlirUnrankedMemRefTypeGetChecked(), mlirUnrankedTensorTypeGet(), mlirUnrankedTensorTypeGetChecked(), mlirUnrankedTensorTypeGetElementType(), mlirValueDump(), mlirValueEqual(), mlirValueGetFirstUse(), mlirValueGetType(), mlirValueIsABlockArgument(), mlirValueIsAOpResult(), mlirValuePrint(), mlirValuePrintAsOperand(), mlirValueReplaceAllUsesOfWith(), mlirVectorTypeGet(), mlirVectorTypeGetChecked(), mlir::PredecessorIterator::PredecessorIterator(), and unwrapList().
wrap()
MlirDiagnostic wrap (mlir::Diagnostic & diagnostic) inline
Definition at line 24 of file Diagnostics.h.
Referenced by getDenseAttribute(), getDenseResource(), mlir::ExternalPass::getDependentDialects(), mlir::ExternalPass::initialize(), mlirAffineAddExprGet(), mlirAffineBinaryOpExprGetLHS(), mlirAffineBinaryOpExprGetRHS(), mlirAffineCeilDivExprGet(), mlirAffineConstantExprGet(), mlirAffineDimExprGet(), mlirAffineExprCompose(), mlirAffineExprGetContext(), mlirAffineFloorDivExprGet(), mlirAffineMapAttrGet(), mlirAffineMapAttrGetValue(), mlirAffineMapCompressUnusedSymbols(), mlirAffineMapConstantGet(), mlirAffineMapEmptyGet(), mlirAffineMapGet(), mlirAffineMapGetContext(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetResult(), mlirAffineMapGetSubMap(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), mlirAffineMapReplace(), mlirAffineMapZeroResultGet(), mlirAffineModExprGet(), mlirAffineMulExprGet(), mlirAffineSymbolExprGet(), mlirAnyQuantizedTypeGet(), mlirArrayAttrGet(), mlirArrayAttrGetElement(), mlirAttributeGetContext(), mlirAttributeGetType(), mlirAttributeGetTypeID(), mlirAttributeParseGet(), mlirBF16TypeGet(), mlirBFloat16TypeGetTypeID(), mlirBlockAddArgument(), mlirBlockArgumentGetOwner(), mlirBlockCreate(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNextInRegion(), mlirBlockGetParentOperation(), mlirBlockGetParentRegion(), mlirBlockGetTerminator(), mlirBoolAttrGet(), mlirBytecodeWriterConfigCreate(), mlirCalibratedQuantizedTypeGet(), mlirComplexTypeGet(), mlirComplexTypeGetElementType(), mlirComplexTypeGetTypeID(), mlirContextAttachDiagnosticHandler(), mlirContextCreate(), mlirContextGetOrLoadDialect(), mlirCreateExternalPass(), mlirDenseBoolArrayGet(), mlirDenseElementsAttrBoolGet(), mlirDenseElementsAttrBoolSplatGet(), mlirDenseElementsAttrDoubleSplatGet(), mlirDenseElementsAttrFloatSplatGet(), mlirDenseElementsAttrGet(), mlirDenseElementsAttrGetSplatValue(), mlirDenseElementsAttrGetStringSplatValue(), mlirDenseElementsAttrGetStringValue(), mlirDenseElementsAttrInt32SplatGet(), mlirDenseElementsAttrInt64SplatGet(), mlirDenseElementsAttrInt8SplatGet(), mlirDenseElementsAttrRawBufferGet(), mlirDenseElementsAttrReshapeGet(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrStringGet(), mlirDenseElementsAttrUInt32SplatGet(), mlirDenseElementsAttrUInt64SplatGet(), mlirDenseElementsAttrUInt8SplatGet(), mlirDenseF32ArrayGet(), mlirDenseF64ArrayGet(), mlirDenseI16ArrayGet(), mlirDenseI32ArrayGet(), mlirDenseI64ArrayGet(), mlirDenseI8ArrayGet(), mlirDiagnosticGetLocation(), mlirDiagnosticGetNote(), mlirDialectGetContext(), mlirDialectGetNamespace(), mlirDialectHandleRegisterDialect(), mlirDialectRegistryCreate(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirElementsAttrGetValue(), mlirExecutionEngineInvokePacked(), mlirF16TypeGet(), mlirF32TypeGet(), mlirF64TypeGet(), mlirFlatSymbolRefAttrGet(), mlirFlatSymbolRefAttrGetValue(), mlirFloat16TypeGetTypeID(), mlirFloat32TypeGetTypeID(), mlirFloat64TypeGetTypeID(), mlirFloat8E4M3B11FNUZTypeGet(), mlirFloat8E4M3B11FNUZTypeGetTypeID(), mlirFloat8E4M3FNTypeGet(), mlirFloat8E4M3FNTypeGetTypeID(), mlirFloat8E4M3FNUZTypeGet(), mlirFloat8E4M3FNUZTypeGetTypeID(), mlirFloat8E5M2FNUZTypeGet(), mlirFloat8E5M2FNUZTypeGetTypeID(), mlirFloat8E5M2TypeGet(), mlirFloat8E5M2TypeGetTypeID(), mlirFloatAttrDoubleGet(), mlirFloatAttrDoubleGetChecked(), mlirFunctionTypeGet(), mlirFunctionTypeGetInput(), mlirFunctionTypeGetResult(), mlirFunctionTypeGetTypeID(), mlirIdentifierGet(), mlirIdentifierGetContext(), mlirIdentifierStr(), mlirIndexTypeGet(), mlirIndexTypeGetTypeID(), mlirInferShapedTypeOpInterfaceInferReturnTypes(), mlirInferShapedTypeOpInterfaceTypeID(), mlirInferTypeOpInterfaceInferReturnTypes(), mlirInferTypeOpInterfaceTypeID(), mlirIntegerAttrGet(), mlirIntegerSetEmptyGet(), mlirIntegerSetGet(), mlirIntegerSetGetConstraint(), mlirIntegerSetGetContext(), mlirIntegerSetReplaceGet(), mlirIntegerTypeGet(), mlirIntegerTypeGetTypeID(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirLLVMArrayTypeGet(), mlirLLVMFunctionTypeGet(), mlirLLVMPointerTypeGet(), mlirLLVMStructTypeLiteralGet(), mlirLLVMVoidTypeGet(), mlirLocationCallSiteGet(), mlirLocationFileLineColGet(), mlirLocationFromAttribute(), mlirLocationFusedGet(), mlirLocationGetAttribute(), mlirLocationGetContext(), mlirLocationNameGet(), mlirLocationUnknownGet(), mlirMemRefTypeContiguousGet(), mlirMemRefTypeContiguousGetChecked(), mlirMemRefTypeGet(), mlirMemRefTypeGetAffineMap(), mlirMemRefTypeGetChecked(), mlirMemRefTypeGetLayout(), mlirMemRefTypeGetMemorySpace(), mlirMemRefTypeGetTypeID(), mlirModuleCreateEmpty(), mlirModuleGetBody(), mlirModuleGetContext(), mlirModuleGetOperation(), mlirNoneTypeGet(), mlirNoneTypeGetTypeID(), mlirOpaqueAttrGet(), mlirOpaqueAttrGetData(), mlirOpaqueAttrGetDialectNamespace(), mlirOpaqueTypeGet(), mlirOpaqueTypeGetData(), mlirOpaqueTypeGetDialectNamespace(), mlirOpaqueTypeGetTypeID(), mlirOperationCreate(), mlirOperationCreateParse(), mlirOpOperandGetNextUse(), mlirOpOperandGetOwner(), mlirOpPassManagerAddPipeline(), mlirOpPassManagerGetNestedUnder(), mlirOpPrintingFlagsCreate(), mlirOpResultGetOwner(), mlirParsePassPipeline(), mlirPassManagerCreate(), mlirPassManagerCreateOnOperation(), mlirPassManagerGetAsOpPassManager(), mlirPassManagerGetNestedUnder(), mlirPDLAttributeTypeGet(), mlirPDLOperationTypeGet(), mlirPDLRangeTypeGet(), mlirPDLRangeTypeGetElementType(), mlirPDLTypeTypeGet(), mlirPDLValueTypeGet(), mlirQuantizedTypeCastExpressedToStorageType(), mlirQuantizedTypeCastFromExpressedType(), mlirQuantizedTypeCastFromStorageType(), mlirQuantizedTypeCastToExpressedType(), mlirQuantizedTypeCastToStorageType(), mlirQuantizedTypeGetExpressedType(), mlirQuantizedTypeGetQuantizedElementType(), mlirQuantizedTypeGetStorageType(), mlirRankedTensorTypeGet(), mlirRankedTensorTypeGetChecked(), mlirRankedTensorTypeGetEncoding(), mlirRankedTensorTypeGetTypeID(), mlirRegionCreate(), mlirRegionGetFirstBlock(), mlirRegionGetNextInOperation(), mlirShapedTypeGetElementType(), mlirSparseElementsAttrGetIndices(), mlirSparseElementsAttrGetValues(), mlirSparseElementsAttribute(), mlirSparseTensorEncodingAttrGet(), mlirSparseTensorEncodingAttrGetDimOrdering(), mlirSparseTensorEncodingAttrGetHigherOrdering(), mlirStridedLayoutAttrGet(), mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirSymbolRefAttrGet(), mlirSymbolRefAttrGetLeafReference(), mlirSymbolRefAttrGetNestedReference(), mlirSymbolRefAttrGetRootReference(), mlirSymbolTableCreate(), mlirSymbolTableGetSymbolAttributeName(), mlirSymbolTableGetVisibilityAttributeName(), mlirSymbolTableInsert(), mlirSymbolTableLookup(), mlirSymbolTableReplaceAllSymbolUses(), mlirSymbolTableWalkSymbolTables(), mlirTransformAnyOpTypeGet(), mlirTransformOperationTypeGet(), mlirTransformOperationTypeGetOperationName(), mlirTransformOperationTypeGetTypeID(), mlirTupleTypeGet(), mlirTupleTypeGetType(), mlirTupleTypeGetTypeID(), mlirTypeAttrGet(), mlirTypeAttrGetValue(), mlirTypeGetContext(), mlirTypeGetDialect(), mlirTypeGetTypeID(), mlirTypeIDAllocatorAllocateTypeID(), mlirTypeIDAllocatorCreate(), mlirTypeIDCreate(), mlirTypeParseGet(), mlirUniformQuantizedPerAxisTypeGet(), mlirUniformQuantizedTypeGet(), mlirUnitAttrGet(), mlirUnrankedMemrefGetMemorySpace(), mlirUnrankedMemRefTypeGet(), mlirUnrankedMemRefTypeGetChecked(), mlirUnrankedMemRefTypeGetTypeID(), mlirUnrankedTensorTypeGet(), mlirUnrankedTensorTypeGetChecked(), mlirUnrankedTensorTypeGetElementType(), mlirUnrankedTensorTypeGetTypeID(), mlirValueGetFirstUse(), mlirValueGetType(), mlirVectorTypeGet(), mlirVectorTypeGetChecked(), mlirVectorTypeGetTypeID(), and mlir::ExternalPass::runOnOperation().