MLIR: lib/Target/LLVMIR/ModuleImport.cpp File Reference
ModuleImport.cpp File Reference
#include "mlir/Target/LLVMIR/ModuleImport.h"
#include "mlir/Target/LLVMIR/Import.h"
#include "AttrKindDetail.h"
#include "DataLayoutImporter.h"
#include "DebugImporter.h"
#include "LoopAnnotationImporter.h"
#include "mlir/Dialect/DLTI/DLTI.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Interfaces/DataLayoutInterfaces.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/ModRef.h"
#include "mlir/Dialect/LLVMIR/LLVMConversionEnumsFromLLVM.inc"
#include "mlir/Dialect/LLVMIR/LLVMOpFromLLVMIRConversions.inc"
Functions
static std::string diag (const llvm::Value &value)
static std::string diagMD (const llvm::Metadata *node, const llvm::Module *module)
static constexpr StringRef getGlobalCtorsVarName ()
Returns the name of the global_ctors global variables.
static constexpr StringRef getGlobalDtorsVarName ()
Returns the name of the global_dtors global variables.
static constexpr StringRef getGlobalMetadataOpName ()
Returns the symbol name for the module-level metadata operation.
static StringRef getLLVMSyncScope (llvm::Instruction *inst)
Converts the sync scope identifier of inst to the string representation necessary to build an atomic LLVM dialect operation.
static SmallVector< int64_t > getPositionFromIndices (ArrayRef< unsigned > indices)
Converts an array of unsigned indices to a signed integer position array.
static LogicalResult convertInstructionImpl (OpBuilder &odsBuilder, llvm::Instruction *inst, ModuleImport &moduleImport)
Converts the LLVM instructions that have a generated MLIR builder.
static SetVector< llvm::BasicBlock * > getTopologicallySortedBlocks (llvm::Function *func)
Get a topologically sorted list of blocks for the given function.
static bool isScalarType (Type type)
Returns if type is a scalar integer or floating-point type.
static Type getVectorTypeForAttr (Type type, ArrayRef< int64_t > arrayShape={})
Returns type if it is a builtin integer or floating-point vector type that can be used to create an attribute or nullptr otherwise.
static Attribute getScalarConstantAsAttr (OpBuilder &builder, llvm::Constant *constScalar)
Returns an integer or float attribute for the provided scalar constant constScalar or nullptr if the conversion fails.
static SmallVector< Attribute > getSequenceConstantAsAttrs (OpBuilder &builder, llvm::ConstantDataSequential *constSequence)
Returns an integer or float attribute array for the provided constant sequence constSequence or nullptr if the conversion fails.
static void processMemoryEffects (llvm::Function *func, LLVMFuncOp funcOp)
static void processPassthroughAttrs (llvm::Function *func, LLVMFuncOp funcOp)
Function Documentation
convertInstructionImpl()
static LogicalResult convertInstructionImpl (OpBuilder & odsBuilder, llvm::Instruction * inst, ModuleImport & moduleImport) static
Converts the LLVM instructions that have a generated MLIR builder.
Using a static implementation method called from the module import ensures the builders have to use the moduleImport argument and cannot directly call import methods. As a result, both the intrinsic and the instruction MLIR builders have to use the moduleImport argument and none of them has direct access to the private module import methods.
Definition at line 121 of file ModuleImport.cpp.
References mlir::failure().
diag()
static std::string diag (const llvm::Value & value) static
Definition at line 50 of file ModuleImport.cpp.
Referenced by alterGpuLaunch(), mlir::transform::detail::applyTransformToEach(), mlir::transform::detail::checkApplyToOne(), checkDoubleConsume(), checkRepeatedConsumptionInOperand(), cloneAndFuseFirstUse(), mlir::lsp::MLIRServer::convertFromBytecode(), mlir::LLVM::ModuleImport::convertGlobals(), mlir::LLVM::ModuleImport::convertValue(), createGpuLaunch(), mlir::DiagnosticEngine::emit(), mlir::detail::DiagnosticEngineImpl::emit(), emitDiag(), mlir::SourceMgrDiagnosticHandler::emitDiagnostic(), mlir::detail::ParallelDiagnosticHandlerImpl::emitDiagnostics(), mlir::Operation::emitError(), mlir::detail::Parser::emitError(), mlir::Operation::emitRemark(), mlir::Operation::emitWarning(), mlir::detail::PassCrashReproducerGenerator::finalize(), findTopLevelTransform(), getLspDiagnoticFromDiag(), mlir::transform::detail::interpreterBaseRunOnOperationImpl(), mlir::pdll::Lexer::Lexer(), mlir::transform::gpu::mapForallToBlocksImpl(), mlir::transform::gpu::mapNestedForallToThreadsImpl(), mlir::transform::gpu::mapOneForallToThreadsImpl(), mlir::RewriterBase::notifyMatchFailure(), mlir::detail::ConversionPatternRewriterImpl::notifyMatchFailure(), mlir::transform::TrackingListener::notifyMatchFailure(), mlir::operator<<(), mlir::detail::ParallelDiagnosticHandlerImpl::ParallelDiagnosticHandlerImpl(), mlir::tracing::FileLineColLocBreakpoint::parseFromString(), mlir::detail::ParallelDiagnosticHandlerImpl::print(), mlir::BytecodeReader::Impl::read(), mlir::DiagnosticEngine::registerHandler(), mlir::detail::ConversionPatternRewriterImpl::remapValues(), rewriteOneForallCommonImpl(), mlir::transform::TransformResults::setMappedValues(), mlir::Op< ConcreteType, Traits >::setPropertiesFromAttr(), mlir::DiagnosedSilenceableFailure::silenceableFailure(), mlir::SourceMgrDiagnosticHandler::SourceMgrDiagnosticHandler(), mlir::SourceMgrDiagnosticVerifierHandler::SourceMgrDiagnosticVerifierHandler(), tileAndFuseFirstExtractUse(), tileAndFuseFirstExtractUseThroughContainingOpBlockArgument(), mlir::transform::tileToForallOpImpl(), mlir::lsp::toJSON(), unpackSingleIndexResultPayloadOperations(), and mlir::detail::ParallelDiagnosticHandlerImpl::~ParallelDiagnosticHandlerImpl().
diagMD()
static std::string diagMD (const llvm::Metadata * node, const llvm::Module * module) static
Definition at line 60 of file ModuleImport.cpp.
getGlobalCtorsVarName()
static constexpr StringRef getGlobalCtorsVarName () static constexpr
Returns the name of the global_ctors global variables.
Definition at line 69 of file ModuleImport.cpp.
Referenced by mlir::LLVM::ModuleImport::convertGlobals().
getGlobalDtorsVarName()
static constexpr StringRef getGlobalDtorsVarName () static constexpr
Returns the name of the global_dtors global variables.
Definition at line 74 of file ModuleImport.cpp.
Referenced by mlir::LLVM::ModuleImport::convertGlobals().
getGlobalMetadataOpName()
static constexpr StringRef getGlobalMetadataOpName () static constexpr
Returns the symbol name for the module-level metadata operation.
It must not conflict with the user namespace.
Definition at line 80 of file ModuleImport.cpp.
getLLVMSyncScope()
static StringRef getLLVMSyncScope (llvm::Instruction * inst) static
Converts the sync scope identifier of inst to the string representation necessary to build an atomic LLVM dialect operation.
Returns the empty string if the operation has either no sync scope or the default system-level sync scope attached. The atomic operations only set their sync scope attribute if they have a non-default sync scope attached.
Definition at line 89 of file ModuleImport.cpp.
getPositionFromIndices()
static SmallVector<int64_t> getPositionFromIndices (ArrayRef< unsigned > indices) static
Converts an array of unsigned indices to a signed integer position array.
Definition at line 109 of file ModuleImport.cpp.
getScalarConstantAsAttr()
static Attribute getScalarConstantAsAttr (OpBuilder & builder, llvm::Constant * constScalar) static
Returns an integer or float attribute for the provided scalar constant constScalar or nullptr if the conversion fails.
Definition at line 680 of file ModuleImport.cpp.
References mlir::emitError(), mlir::get(), mlir::FloatType::getBF16(), mlir::Builder::getContext(), mlir::Builder::getFloatAttr(), mlir::LLVM::detail::getFloatType(), and mlir::Builder::getIntegerAttr().
Referenced by getSequenceConstantAsAttrs().
getSequenceConstantAsAttrs()
static SmallVector<Attribute> getSequenceConstantAsAttrs (OpBuilder & builder, llvm::ConstantDataSequential * constSequence) static
Returns an integer or float attribute array for the provided constant sequence constSequence or nullptr if the conversion fails.
Definition at line 711 of file ModuleImport.cpp.
References getScalarConstantAsAttr().
getTopologicallySortedBlocks()
static SetVector<llvm::BasicBlock *> getTopologicallySortedBlocks (llvm::Function * func) static
Get a topologically sorted list of blocks for the given function.
Definition at line 135 of file ModuleImport.cpp.
getVectorTypeForAttr()
static Type getVectorTypeForAttr (Type type, ArrayRef< int64_t > arrayShape = {}) static
Returns type if it is a builtin integer or floating-point vector type that can be used to create an attribute or nullptr otherwise.
If provided, arrayShape is added to the shape of the vector to create an attribute that matches an array of vectors.
Definition at line 633 of file ModuleImport.cpp.
isScalarType()
static bool isScalarType (Type type) static
Returns if type is a scalar integer or floating-point type.
Definition at line 625 of file ModuleImport.cpp.
processMemoryEffects()
static void processMemoryEffects (llvm::Function * func, LLVMFuncOp funcOp) static
Definition at line 1520 of file ModuleImport.cpp.
References mlir::get().
Referenced by mlir::LLVM::ModuleImport::processFunctionAttributes().
processPassthroughAttrs()
static void processPassthroughAttrs (llvm::Function * func, LLVMFuncOp funcOp) static
Definition at line 1537 of file ModuleImport.cpp.
References mlir::emitWarning(), and mlir::get().
Referenced by mlir::LLVM::ModuleImport::processFunctionAttributes().